### ISSUE TITLE
Outdated tau code to be removed

### ISSUE THREAD

**Issue by jpata** [cms-sw/cmssw#37974]
These modules cannot run (and are not used anywhere in CMSSW) because they rely on outdated and removed functionality.
```
RecoTauTag/ImpactParameter:
  ImpactParameter:
  - 'ImpactParameter::produce(edm::Event &, const edm::EventSetup &); '
  PFTau3ProngReco:
  - 'PFTau3ProngReco::produce(edm::Event &, const edm::EventSetup &); '
```

@cms-sw/tau-pog-l2 @mbluj can you please remove them?
